### ISSUE TITLE
Could not start tslint-to-eslint

### ISSUE THREAD

**Issue by KSib** [typescript-eslint/tslint-to-eslint-config#997] opened 2021-03-19 19:38 UTC
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: 2.20.
-   ESLint version: 7.22.0
-   Node version: 6.14.11

#### Actual Behavior

I run 
```npx tslint-to-eslint-config```
from my ClientApp directory and then I get this message

npx: installed 60 in 4.963s
❌ Could not start tslint-to-eslint: ❌
  Could not import the "eslint-plugin-node" module. Do you need to install packages?

#### Expected Behavior

I'd like it to not error out

I was following this guide and eventually wound up here since it isn't working.
https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration

**Comment by JoshuaKGoldberg** [comment] 2021-03-19 19:48
Hi @KSib, thanks for posting an issue! I too would prefer it to not error out.

> from my ClientApp directory

Could you please post a link to the repo, or generally some self-contained way to reproduce your issue? It's hard to help without.

> Could not import the "eslint-plugin-node" module. Do you need to install packages?

Do you need to install `eslint-plugin-node`? 😄 

> this guide

Which guide are you referring to? One of the docs files in this repo?

**Comment by KSib** [comment] 2021-03-19 19:53
Oops, sorry. Forgot to paste the link to the guide I was following. I updated the initial post.

I tried this
`npm install --save-dev eslint-plugin-node `

and then running

`npx tslint-to-eslint-config`

Same error

I don't have a repo I can copy this to. I was hoping to maybe just be directed to where I can investigate this further, like a verbose output flag or maybe if someone just ran into this before and has a fix or workaround.

**Comment by JoshuaKGoldberg** [comment] 2021-03-19 20:55
Gotcha, thanks for the update! There should be more logs in a file like `tslint-to-eslint-config.log`.

**Comment by KSib** [comment] 2021-03-19 20:58
Interesting! I did find the file, but unfortunately there is nothing in it. Completely blank. Should there be something in it?

**Comment by jafin** [comment] 2021-03-21 07:54
I got same error when running on this repo. https://github.com/ecirpnaes/SimpleDataScripter  Log file tslint-to-eslint-config.log exists but is 0 bytes.

**Comment by JoshuaKGoldberg** [comment] 2021-05-10 05:47
Welp, I have no issues with roughly the same settings on Node 14.7.0 and on Node 16.1.0.

```
C:\Code>git clone https://github.com/ecirpnaes/SimpleDataScripter
Cloning into 'SimpleDataScripter'...
remote: Enumerating objects: 171, done.
remote: Counting objects: 100% (171/171), done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 171 (delta 88), reused 118 (delta 45), pack-reused 0
Receiving objects: 100% (171/171), 2.33 MiB | 15.32 MiB/s, done.
Resolving deltas: 100% (88/88), done.

C:\Code>cd SimpleDataScripter

C:\Code\SimpleDataScripter>npx tslint-to-eslint-config

✨ 8 rules replaced with their ESLint equivalents. ✨

❗ 1 ESLint rule behaves differently from its TSLint counterpart ❗
  Check ./tslint-to-eslint-config.log for details.

☠ Prettier plugins are missing from your configuration. ☠
  We highly recommend running tslint-to-eslint-config --prettier to disable formatting ESLint rules.
  See https://github.com/typescript-eslint/tslint-to-eslint-config/blob/master/docs/FAQs.md#should-i-use-prettier.

⚡ 3 new packages are required for this ESLint configuration. ⚡
  npm install @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint --save-dev

♻ Consider using --comments to replace TSLint comment directives in your source files. ♻

✅ All is well! ✅
```

If `tslint-to-eslint-config` ever gives you a message like:

```
Could not import the "eslint-plugin-abc" module. Do you need to install packages?
```

Try installing that `eslint-plugin-abc` module, i.e. `npm i eslint-plugin-abc`.

I'm going to close this thread as non-actionable because I can't reproduce this error, it appears to be working under at least `wsl2`, and the original error message indicates what to do. Please let me know if this is still an issue for you and we can continue the discussion! 💖

**Closed by JoshuaKGoldberg** 2021-05-10 05:47 UTC
Labels: status: needs more information
