### ISSUE TITLE
Missing merger: @typescript-eslint/consistent-type-assertions

### ISSUE THREAD

**Issue by kuldeeps48** [typescript-eslint/tslint-to-eslint-config#339] opened 2020-02-21 08:33 UTC
### 💥 Missing Merger

-   `tslint-to-eslint-config` version: 0.5.1
-   ESLint version: 6.8.0

#### CLI Output

`✨ 90 rules replaced with their ESLint equivalents. ✨

❗ 7 ESLint rules behave differently from their TSLint counterparts ❗
  * no-unused-expressions:
    - The TSLint optional config "allow-new" is the default ESLint behavior and will no longer be ignored.
  * camelcase:
    - Leading and trailing underscores (_) in variable names will now be ignored.
  * no-underscore-dangle:
    - Leading or trailing underscores (_) on identifiers will now be forbidden.
  * no-invalid-this:
    - Functions in methods will no longer be ignored.
  * prefer-arrow/prefer-arrow-functions:
    - ESLint does not support allowing standalone function declarations.
    - ESLint does not support allowing named functions defined with the function keyword.
  * eqeqeq:
    - Option "smart" allows for comparing two literal values, evaluating the value of typeof and null comparisons.
  * no-redeclare:
    - ESLint does not support check-parameters.

❌ 1 error thrown. ❌
  Check ./tslint-to-eslint-config.log for details.

❓ 4 rules do not yet have ESLint equivalents ❓
  See generated log file; defaulting to eslint-plugin-tslint for these rules.

⚡ 3 packages are required for new ESLint rules. ⚡
  import
  prefer-arrow
  eslint-plugin-import

❓ 2 editor settings do not yet have ESLint equivalents ❓
  See generated log file.
✅ All is well! ✅`

#### File Output

`Error: multiple output @typescript-eslint/consistent-type-assertions ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.
Please file an issue at https://github.com/typescript-eslint/tslint-to-eslint-config/issues/new?template=missing_merger.md 🙏

[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "jsdoc-format"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-promise-as-boolean"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-reference-import"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "prefer-conditional-expression"[39m
[33m[39m[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "editor.autoClosingBrackets"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "editor.formatOnSave"[39m
[33m[39m`

**Comment by JoshuaKGoldberg** [comment] 2020-03-14 05:18
Thanks for this, and sorry about the delay!

Marking this issue as a duplicate of #343 because that one has a full reproduction.

**Closed by JoshuaKGoldberg** 2020-03-14 05:18 UTC
Labels: type: missing merger
