### ISSUE TITLE
Missing merger: whitespace, spacing, one-line

### ISSUE THREAD

**Issue by gliluaume** [typescript-eslint/tslint-to-eslint-config#401] opened 2020-04-24 09:33 UTC
Hi, `tslint-to-eslint-config` just asked me to open an issue. I feel sorry in advance because the informations I can provide here might be insufficient to reproduce the issue. But I hope this nevertheless could help.

### 💥 Missing Merger

-   `tslint-to-eslint-config` version: 0.6.0
-   ESLint version: 4.19.1

#### CLI Output
```
$> npx tslint-to-eslint-config
✨ 79 rules replaced with their ESLint equivalents. ✨

❗ 7 ESLint rules behave differently from their TSLint counterparts ❗
  * camelcase:
    - Leading undescores in variable names will now be ignored.
  * no-underscore-dangle:
    - Leading and trailing underscores (_) on identifiers will now be ignored.
  * no-invalid-this:
    - Functions in methods will no longer be ignored.
  * no-unused-expressions:
    - The TSLint optional config "allow-new" is the default ESLint behavior and will no longer be ignored.
  * prefer-arrow/prefer-arrow-functions:
    - ESLint does not support allowing standalone function declarations.
    - ESLint does not support allowing named functions defined with the function keyword.
  * space-before-function-paren:
    - Option "constructor" is not supported by ESLint.
    - Option "method" is not supported by ESLint.
  * eqeqeq:
    - Option "smart" allows for comparing two literal values, evaluating the value of typeof and null comparisons.

❌ 1 error thrown. ❌
  Check ./tslint-to-eslint-config.log for details.

❓ 4 rules do not yet have ESLint equivalents ❓
  See generated log file; defaulting to eslint-plugin-tslint for these rules.

⚡ 3 packages are required for new ESLint rules. ⚡
  import
  eslint-plugin-jsdoc
  prefer-arrow

✅ All is well! ✅
```

#### File Output
```
$> cat ./tslint-to-eslint-config.log
Error: multiple output @typescript-eslint/triple-slash-reference ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.
Please file an issue at https://github.com/typescript-eslint/tslint-to-eslint-config/issues/new?template=missing_merger.md 🙏

tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "import-spacing"
tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-unused-variable"
tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "one-line"
tslint-to-eslint-config does not know the ESLint equivalent for TSLint's "whitespace"
```

#### Reproduction
I am not able to provide a full repository. So please find what I can publish here as attached files.
[config.zip](https://github.com/typescript-eslint/tslint-to-eslint-config/files/4527887/config.zip)

**Comment by gliluaume** [comment] 2020-04-24 09:41
Another point. `tslint-to-eslint-config` displays:
⚡ 3 packages are required for new ESLint rules. ⚡
  import
  eslint-plugin-jsdoc
  prefer-arrow

Shouldn't it be:
⚡ 3 packages are required for new ESLint rules. ⚡
  eslint-plugin-import 
  eslint-plugin-jsdoc 
  eslint-plugin-prefer-arrow

**Comment by JoshuaKGoldberg** [comment] 2020-04-26 03:24
Thanks for reporting @gliluaume! This is actually a duplicate of #400:

> Error: multiple output @typescript-eslint/triple-slash-reference ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.

The files you posted are enough to reproduce the issue, so this'll be useful in addition to the separate repro steps there. Thank you for going the extra step to share even though the repository isn't open source. 😄 

> Shouldn't it be:

Correct, and separately fixed in #404. Good eye!

**Closed by JoshuaKGoldberg** 2020-04-26 03:24 UTC

**Comment by JoshuaKGoldberg** [comment] 2020-04-26 03:30
As for the missing rules, per the [typescript-eslint roadmap](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md):

* `brace-style`: filed #410
* `no-unused-variable`: filed #411
* `whitespace`: doesn't have an ESLint equivalent (#348)

**Comment by gliluaume** [comment] 2020-04-27 08:52
Ok, thank you! Sorry for having created a duplicate :)
