### ISSUE TITLE
Missing merger error

### ISSUE THREAD

**Issue by emilio-notable** [typescript-eslint/tslint-to-eslint-config#324] opened 2020-02-09 17:25 UTC
### 💥 Missing Merger

-   `tslint-to-eslint-config` version: 0.5.0 (when running `npx tslint-to-eslint-config --version`, because i don't have it in my package.json)
-   ESLint version: 6.8.0 (when running `npx eslint --version`, because i don't have it in my package.json)

#### CLI Output

```
npx: installed 54 in 5.208s
✨ 88 rules replaced with their ESLint equivalents. ✨

❗ 10 ESLint rules behave differently from their TSLint counterparts ❗
  * no-invalid-this:
    - Functions in methods will no longer be ignored.
  * no-unused-expressions:
    - The TSLint optional config "allow-new" is the default ESLint behavior and will no longer be ignored.
  * prefer-arrow/prefer-arrow-functions:
    - ESLint does not support allowing standalone function declarations.
    - ESLint does not support allowing named functions defined with the function keyword.
  * space-before-function-paren:
    - Option "constructor" is not supported by ESLint.
    - Option "method" is not supported by ESLint.
  * comma-dangle:
    - ESLint does not support config property esSpecCompliant
  * eqeqeq:
    - Option "smart" allows for comparing two literal values, evaluating the value of typeof and null comparisons.
  * camelcase:
    - Leading and trailing underscores (_) in variable names will now be ignored.
    - ESLint's camel-case rule does not allow pascal or snake case variable names. Those cases are reserved for class names and static methods.
  * no-underscore-dangle:
    - Leading or trailing underscores (_) on identifiers will now be forbidden.
  * no-redeclare:
    - ESLint does not support check-parameters.
  * @typescript-eslint/space-within-parens:
    - The number of spaces will be ignored

❌ 1 error thrown. ❌
  Check ./tslint-to-eslint-config.log for details.
 ️
❓ 7 rules do not yet have ESLint equivalents ❓
  See generated log file; defaulting to eslint-plugin-tslint for these rules.

⚡ 3 packages are required for new ESLint rules. ⚡
  prefer-arrow
  import
  eslint-plugin-import

✅ All is well! ✅
```

#### File Output

```
Error: multiple output @typescript-eslint/consistent-type-assertions ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.
Please file an issue at https://github.com/typescript-eslint/tslint-to-eslint-config/issues/new?template=missing_merger.md 🙏

import-spacing does not yet have an ESLint equivalent.
jsdoc-format does not yet have an ESLint equivalent.
no-reference-import does not yet have an ESLint equivalent.
object-literal-sort-keys does not yet have an ESLint equivalent.
one-line does not yet have an ESLint equivalent.
prefer-conditional-expression does not yet have an ESLint equivalent.
whitespace does not yet have an ESLint equivalent.
```

#### Reproduction

I was able to reproduce the error with just these two files (and running `npm install`)

package.json
```
{
  "name": "tesst",
  "version": "0.0.0",
  "private": true,
  "dependencies": {},
  "devDependencies": {
    "tslint": "^5.20.1",
    "typescript": "^3.7.5"
  }
}
```

tslint.json
```
{
  "extends": ["tslint:latest"],
  "rules": {}
}
```

**Comment by JoshuaKGoldberg** [comment] 2020-02-09 23:53
Indeed! Duplicate of #321.

**Closed by JoshuaKGoldberg** 2020-02-09 23:53 UTC
