### ISSUE TITLE
multiple output @typescript-eslint/triple-slash-reference ESLint rule options were generated

### ISSUE THREAD

**Issue by WizardPC** [typescript-eslint/tslint-to-eslint-config#397] opened 2020-04-21 16:27 UTC
### 💥 Missing Merger

-   `tslint-to-eslint-config` version: latest
-   ESLint version: 6.8.0

#### CLI Output

```
✨ 73 rules replaced with their ESLint equivalents. ✨

❗ 7 ESLint rules behave differently from their TSLint counterparts ❗
  * no-console:
    - Custom console methods, if they exist, will no longer be allowed.
  * no-invalid-this:
    - Functions in methods will no longer be ignored.
  * no-unused-expressions:
    - The TSLint optional config "allow-new" is the default ESLint behavior and will no longer be ignored.
  * prefer-arrow/prefer-arrow-functions:
    - ESLint does not support allowing standalone function declarations.
    - ESLint does not support allowing named functions defined with the function keyword.
  * eqeqeq:
    - Option "smart" allows for comparing two literal values, evaluating the value of typeof and null comparisons.
  * camelcase:
    - Leading undescores in variable names will now be ignored.
    - ESLint's camel-case rule does not allow pascal or snake case variable names. Those cases are reserved for class names and static methods.
  * no-underscore-dangle:
    - Leading and trailing underscores (_) on identifiers will now be ignored.

❌ 1 error thrown. ❌
  Check ./tslint-to-eslint-config.log for details.

❓ 17 rules do not yet have ESLint equivalents ❓
  See generated log file; defaulting to eslint-plugin-tslint for these rules.

⚡ 4 packages are required for new ESLint rules. ⚡
  eslint-plugin-import
  eslint-plugin-jsdoc
  import
  prefer-arrow

✅ All is well! ✅
```

#### File Output

```
Error: multiple output @typescript-eslint/triple-slash-reference ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.
Please file an issue at https://github.com/typescript-eslint/tslint-to-eslint-config/issues/new?template=missing_merger.md 🙏

[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "component-class-suffix"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "component-selector"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "contextual-lifecycle"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "directive-class-suffix"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "directive-selector"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-conflicting-lifecycle"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-host-metadata-property"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-input-rename"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-inputs-metadata-property"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-output-native"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-output-on-prefix"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-output-rename"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-outputs-metadata-property"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "template-banana-in-box"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "template-no-negated-async"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "use-lifecycle-interface"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "use-pipe-transform-interface"[39m
[33m[39m
```

**Comment by JoshuaKGoldberg** [comment] 2020-04-26 03:17
Thanks for reporting @WizardPC! Indeed, there should be a merger added. Although this issue was filed first I'll close it as a dup of #400 because that one has reproduction steps.

**Closed by JoshuaKGoldberg** 2020-04-26 03:17 UTC
