### ISSUE TITLE
Missing Merger

### ISSUE THREAD

**Issue by pavsaund** [typescript-eslint/tslint-to-eslint-config#375] opened 2020-04-05 08:52 UTC
### 💥 Missing Merger

-   `tslint-to-eslint-config` version: ?
-   `@typescript-eslint/eslint-plugin` version: 2.26.0
-   ESLint version: 6.8.0

I'm following https://code.visualstudio.com/api/advanced-topics/tslint-eslint-migration and encountered the missing merger issue. I'm unclear on what the next steps are regarding this specific issue is, but reporting the issue as requested in the log output.

#### CLI Output

```sh
✨ 92 rules replaced with their ESLint equivalents. ✨

❗ 7 ESLint rules behave differently from their TSLint counterparts ❗
  * camelcase:
    - Leading undescores in variable names will now be ignored.
  * no-underscore-dangle:
    - Leading and trailing underscores (_) on identifiers will now be ignored.
  * no-invalid-this:
    - Functions in methods will no longer be ignored.
  * no-unused-expressions:
    - The TSLint optional config "allow-new" is the default ESLint behavior and will no longer be ignored.
  * prefer-arrow/prefer-arrow-functions:
    - ESLint does not support allowing standalone function declarations.
    - ESLint does not support allowing named functions defined with the function keyword.
  * eqeqeq:
    - Option "smart" allows for comparing two literal values, evaluating the value of typeof and null comparisons.
  * no-redeclare:
    - ESLint does not support check-parameters.

❌ 1 error thrown. ❌
  Check ./tslint-to-eslint-config.log for details.

❓ 5 rules do not yet have ESLint equivalents ❓
  See generated log file; defaulting to eslint-plugin-tslint for these rules.

⚡ 3 packages are required for new ESLint rules. ⚡
  prefer-arrow
  import
  eslint-plugin-import

✅ All is well! ✅
```

##### tslint-to-eslint-config.log
```.log
Error: multiple output @typescript-eslint/consistent-type-assertions ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.
Please file an issue at https://github.com/typescript-eslint/tslint-to-eslint-config/issues/new?template=missing_merger.md 🙏

[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "jsdoc-format"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "no-reference-import"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "object-literal-sort-keys"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "prefer-conditional-expression"[39m
[33mtslint-to-eslint-config does not know the ESLint equivalent for TSLint's "prettier"[39m
[33m[39m
```

##### tsconfig.json
```json
{
    "extends": "./node_modules/@dolittle/typescript.build/TSConfig/tsconfig.base.json",
    "compilerOptions": {
        "baseUrl": "./Features",
        "sourceMap": true,
        "inlineSourceMap": false,
        "inlineSources": false,
        "noImplicitAny": false,
        "target": "es5",
        "module": "esnext",
        "moduleResolution": "node",
        "allowJs": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "declaration": false,
        "strict": false,
        "lib": ["es2019", "dom"],
    },
    "include": [
        "./custom_typings/**/*.d.ts",
        "./**/*.ts"
    ],
    "exclude": [
        "node_modules",
        "aurelia_project"
    ]
}
```

##### tsconfig.base.json
```json
{
  "compilerOptions": {
    "lib": ["es2017", "dom"],
    "module": "commonjs",
    "target": "es2015",
    "esModuleInterop": true,
    "stripInternal": true,
    
    "declaration": true,

    "strict": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,

    "moduleResolution": "node",
    "inlineSourceMap": true,
    "inlineSources": true,

    "downlevelIteration": true,
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

##### .prettierrc
```json
{
    "tabWidth": 4,
    "singleQuote": true,
    "printWidth": 120,
    "trailingComma": "none"
}
```

**Comment by JoshuaKGoldberg** [comment] 2020-04-08 14:54
Thanks so much for filing @pavsaund! I believe this is a duplicate of #321 actually. Will work on a fix soon!

**Closed by JoshuaKGoldberg** 2020-04-08 14:54 UTC
