### ISSUE TITLE
Missing merger: member-delimiter-style

### ISSUE THREAD

**Issue by beingbing** [typescript-eslint/tslint-to-eslint-config#247] opened 2019-10-21 06:40 UTC
### 💥 Missing Merger

-   `tslint` version: 5.18.0
-   `ESLint` version: 6.5.1

#### File Output

```
Error: multiple output @typescript-eslint/member-delimiter-style ESLint rule options were generated, but tslint-to-eslint-config doesn't have "merger" logic to deal with this.
```

#### CLI Output

```
📢 6 ESLint rules behave differently from their TSLint counterparts: 📢
* no-console:
  - Custom console methods, if they exist, will no longer be allowed.
* no-invalid-this:
  - Functions in methods will no longer be ignored.
* no-unused-expressions:
  - The TSLint optional config "allow-new" is the default ESLint behavior and will no longer be ignored.
* eqeqeq:
  - Option "smart" allows for comparing two literal values, evaluating the value of typeof and null comparisons.
* camelcase:
  - Leading undescores in variable names will now be ignored.
  - ESLint's camel-case rule does not allow pascal or snake case variable names. Those cases are reserved for class names and static methods.
* no-underscore-dangle:
  - Leading and trailing underscores (_) on identifiers will now be ignored.
💀 1 error thrown. 💀
Check ./tslint-to-eslint-config.log for details.
️👀 30 rules do not yet have ESLint equivalents; defaulting to eslint-plugin-tslint. 👀
```

#### Reproduction

run 
`npx tslint-to-eslint-config`

**Comment by JoshuaKGoldberg** [comment] 2019-10-22 01:05
Hi @beingbing, thanks for filing this issue! 

Without more information on your original TSLint configuration it'll be hard to address this issue. Per the template you started with on this issue:

> Please paste a link to a repository, Gist, or other means of reproducing your error here.
> Note that `tslint-to-eslint-config` includes information from `package.json`, `tsconfig.json`, and other files, so just your TSLint configuration may not be enough.

**Comment by JoshuaKGoldberg** [comment] 2019-10-26 15:42
Duplicate of #254. 🚀

**Closed by JoshuaKGoldberg** 2019-10-26 15:42 UTC
Labels: status: needs more information, type: missing merger
