### ISSUE TITLE
Core ESLint rules not disabled when their @typescript-eslint equivalent is enabled

### ISSUE THREAD

**Issue by JamesHenry** [typescript-eslint/tslint-to-eslint-config#1509] opened 2022-06-12 09:57 UTC
### 🐛 Bug Report

-   `tslint-to-eslint-config` version: `2.13.0`
-   ESLint version: N/A
-   Node version: `16.15.0`

#### Actual Behavior

Found when updating angular-eslint's usage of tslint-to-eslint-config

See my minimal repro, e.g. `quotes` and `semi`  are both enabled despite their typescript-eslint counterparts also being present and enabled.

This is a regression because this didn't use to happen in `2.4.0` which is where I am migrating from (yes I know quite a way behind!)

#### Expected Behavior

`quotes` and `semi` should be explicitly be set to `off`

#### Reproduction

Minimal repro here: https://github.com/JamesHenry/tslint-to-eslint-config-repro

- First commit adds tslint and codelyzer (Angular specific TSLint rules)
- Second commit is simply the result of running `npx tslint-to-eslint-config`, see the generated .eslintrc.js

**Comment by JamesHenry** [comment] 2022-06-12 09:57
This is a continuation of #1207

**Comment by neel-desh** [comment] 2022-06-12 16:45
Is this open for contribution? if yes, can I pick it up?

**Comment by JoshuaKGoldberg** [comment] 2022-06-12 17:13
Absolutely, yes please @neel-desh! 🚀

**Comment by JoshuaKGoldberg** [comment] 2022-10-13 01:26
Sorry for taking so long on this @JamesHenry, it fell off my radar! I just tried locally with the latest, `tslint-to-eslint-config@2.13.3`, and get an `.eslintrc.js` with `"quotes": "off"` and `"semi": "off"`. Does this issue still repro for you?

**Comment by hyperupcall** [comment] 2022-12-02 03:30
Since I made the PR that closed #1207, I checked this out and for me I get the expected behavior in both cases: `"quotes: "off", "semi": "off"`, when running locally and through `npx`.

**Comment by JoshuaKGoldberg** [comment] 2022-12-02 16:36
Great - in that case I'll close this out. Thanks for investigating @hyperupcall!

If anybody is experiencing this behavior as broken, please do post back here or in a new issue with full reproduction steps we can take.

**Closed by JoshuaKGoldberg** 2022-12-02 16:36 UTC
Labels: type: bug, status: needs more information
