### ISSUE TITLE
tslint-to-eslint-config.log Missing merge logic

### ISSUE THREAD

**Issue by DerHerrGammler** [typescript-eslint/tslint-to-eslint-config#322] opened 2020-02-07 14:32 UTC
### 💥 Missing Merger

-   `tslint-to-eslint-config` version: X.X.X
-   ESLint version: 6.8.0

#### Reproduction

[33mencoding does not yet have an ESLint equivalent.[39m
[33mimport-spacing does not yet have an ESLint equivalent.[39m
[33mjsdoc-format does not yet have an ESLint equivalent.[39m
[33mmatch-default-export-name does not yet have an ESLint equivalent.[39m
[33mno-boolean-literal-compare does not yet have an ESLint equivalent.[39m
[33mno-dynamic-delete does not yet have an ESLint equivalent.[39m
[33mno-mergeable-namespace does not yet have an ESLint equivalent.[39m
[33mno-reference-import does not yet have an ESLint equivalent.[39m
[33mno-unnecessary-callback-wrapper does not yet have an ESLint equivalent.[39m
[33mno-unused-variable does not yet have an ESLint equivalent.[39m
[33mnumber-literal-format does not yet have an ESLint equivalent.[39m
[33mone-line does not yet have an ESLint equivalent.[39m
[33mprefer-method-signature does not yet have an ESLint equivalent.[39m
[33mprefer-while does not yet have an ESLint equivalent.[39m
[33mreturn-undefined does not yet have an ESLint equivalent.[39m
[33mstrict-type-predicates does not yet have an ESLint equivalent.[39m
[33mswitch-final-break does not yet have an ESLint equivalent.[39m
[33mtypedef does not yet have an ESLint equivalent.[39m
[33mwhitespace does not yet have an ESLint equivalent.[39m
[33m[39m

**Comment by JoshuaKGoldberg** [comment] 2020-02-09 23:54
Hi @DerHerrGammler, thanks for filing an issue! Unfortunately there's not enough information in your description to take action. #321 is an example of an issue for missing merge logic that includes `tslint-to-eslint-config.log`'s information.

If this issue isn't a duplicate of #321, please do post that file's contents and I can take a look. ✔️

**Closed by JoshuaKGoldberg** 2020-02-09 23:54 UTC
